### ISSUE TITLE
Rozdzielczość

### ISSUE THREAD

**Issue by Adrianoo02** [kpl-addons/plugin.video.tvpgo#10]
Witam.

Czy jest możliwość zmiany rozdzielczości kanałów na żywo? wszystkie działają mi w 1024x576. Jest taka możliwość by uruchomiać je w 1080 tak jak w aplikacji na Androida?

**Comment by Adrianoo02** [comment]
KODI 19.4 , Windows 10, ekran 1920x1080

**Comment by Mariusz89B** [comment]
Ustaw w isa min. Bitrate na 10000000

**Comment by Adrianoo02** [comment]
Gdzie znajdę te ustawienia?

**Comment by Cinek77** [comment]
Później w ustawieniach obrazu można wybrać jakość
https://prnt.sc/wVc4rBM4FhAY

**Comment by Adrianoo02** [comment]
Dzięki, o to właśnie chodziło :)
