### ISSUE TITLE
Catchup w PVR IPTV Simple Client

### ISSUE THREAD

**Issue by Just123yna** [kpl-addons/plugin.video.tvpgo#11]
Cześć
czy korzystając z wtyczki TVP GO, da się ustawić catchup dla TVP w kliencie IPTV (archiwum we wtyczce działa prawidłowo)?
Być może rzecz sprowadza się do właściwego "Query format string", ale nie potrafię znaleźć prawidłowego ustawienia.

Pzdr

**Comment by heppenowski** [comment]
Cześć,
Niestety w tej wersji wtyczki to nie zadziała, nie ważne jaki query format string ustawisz. Po prostu generowana lista nie zawiera odpowiedniego ciągu, jak i sama wtyczka nie jest przystosowana do działania funkcji catchup z IPTV Simple Client.

Całe szczęście udało mi się to zaimplementować w nowej wtyczce TVP, nad którą obecnie trwają prace. Wtyczka jest już w dość zaawansowanym stopniu skończona, link do repo na githubie: https://github.com/kpl-addons/plugin.video.kpl.tvp
Więcej na temat wtyczki przeczytasz na KWP: https://forum.kodiwpigulce.pl/showthread.php?tid=4568

Sama funkcja powinna działać (w KPL.TVP) na ustawieniach domyślnych Simple Clienta, tj. pusty query format string oraz czas przesunięcia przed rozpoczęciem programu ustawiony na 5 minut.
W razie pytań, na KWP w temacie, albo otwórz issue w drugim repo.
