### ISSUE TITLE
Wtyczka nie działa

### ISSUE THREAD

**Issue by Gelip** [kpl-addons/plugin.video.tvpgo#12]
Coś jest nie tak. Wtyczka się uruchamia, wchodzę w TVP GO ale w Archiwum już nie da rady - długo mieli Proszę czekać i w końcu Błąd. Czasem uda się wyświetlić listę ale odtworzyć się nie da - raz nawet Kodi się wyłączyło.

**Comment by DenDyGH** [comment]
Cześć, zachęcamy do przejścia na nową wtyczkę: TVP (Libka). Znajdziesz ją w tym samym repozytorium, czyli KWP lub KPL-Addons.
A github tutaj: https://github.com/kpl-addons/plugin.video.kpl.tvp

**Comment by Gelip** [comment]
OK, ale postanowiłem sprawdzić jedną rzecz. Kodi mam na SmartTV BOX z Androidem a Internet na nim ze smartfona przez Wifi. Dwa dni temu zmieniłem smartfon i dopiero dzić odpaliłem na nim Kodi i TVP GO i zauważyłem problem. Teraz wróciłem do starego smartfona i TVP GO działa. Nie wiem - albo to była tylko wina przeciążonych serwerów TVP albo faktycznie na innym smartfonie coś jest nie tak - tylko iż w laptopie Internet działa normalnie.
Poużywam i zobaczę jak będzie.

**Comment by Gelip** [comment]
To chyba jednak było coś z Internetem albo serwerami TVP bo wróciłem na drugi smartfon i teraz TVP GO działa :-)

**Comment by DenDyGH** [comment]
Wszystko możliwe, najważniejsze, że teraz działa. Miłego oglądania ;)
