### ISSUE TITLE
1.3.6 materiały VOD rozdzielczość tylko sd

### ISSUE THREAD

**Issue by t0mciu** [kpl-addons/plugin.video.tvpgo#5]
Nie wiem, czy to tylko u mnie, ale po zainstalowaniu najnowszej wersji 1.3.6 materiały VOD odtwarzają się tylko w SD, i nie ma możliwości zmiany rozdzielczości. Na wszystkich wcześniejszych wersjach do 1.3.5 włącznie, odtwarza się domyślnie w FHD. 

Sprzęt to Asrock J3455B (grafika HD500 z HW decode), Debian 11, Kodi 19.4, Phyton 3.9.2. Wszystko na bieżąco aktualizowane z repo debian stable i deb.multimedia.

Ostatni test wykonany na serialu Ranczo, na tym samym odcinku. Do wersji 1.3.5 włącznie, działa FHD. W wersji 1.3.6 tylko 480SD. Log poniżej:
[kodi.log](https://github.com/kpl-addons/plugin.video.tvpgo/files/8639409/kodi.log)

**Comment by DenDyGH** [comment]
Nowa wersja powinna rozwiązać problem, wkrótce pojawi się w repozytorium.
https://github.com/kpl-addons/plugin.video.tvpgo/releases/tag/v1.3.7

**Comment by t0mciu** [comment]
Wygląda, że VOD jest ok. Do pełni szczęścia brakuje jeszcze pobierania opisów (epg) danego filmu lub odcinka serialu.

**Comment by DenDyGH** [comment]
Trwają prace nad nową wtyczką, w której będą zawarte wszystkie serwisy TVP.
I tam opisy powinny się już pojawić :)
