### ISSUE TITLE
Wtyczka w kodi nie działa

### ISSUE THREAD

**Issue by Doliwa79** [kpl-addons/plugin.video.tvpgo#9]
Dziś wtyczka w kodi przestała działać. Kodi 19.3 nie działa żaden kanał.

**Comment by hevet** [comment]
Instalowaleś nową wersję?

**Comment by Doliwa79** [comment]
Mam wasze repozytorium a w nim najnowsza wersja to 1.3.7 na stronie mam 1.3.8
Jak mogę ją zaktualizować

**Comment by hevet** [comment]
[plugin.video.tvpgo-main(1).zip](https://github.com/kpl-addons/plugin.video.tvpgo/files/9126281/plugin.video.tvpgo-main.zip)

Pobierz i zainstaluj z pliku .zip.

**Comment by DenDyGH** [comment]
Nowa wersja do repo zostanie dodana jutro.
Na ten moment tylko ręczna aktualizacja.

**Comment by Doliwa79** [comment]
ok dziękuję za informację

**Comment by DenDyGH** [comment]
Poszło do repo.
